config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :emails
  resources :products
  get "/:category_id/:page", to: "products#index"
  resources :logins
  get "/login", to: "logins#new"
  get "users/:id/edit/:category", to: "users#edit"
  get "users/edit", to: "users#show"
  root 'splash#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
end

app/models/email.rb
class Email < ApplicationRecord
  def send_email(user_id)
    RestClient.post("http://localhost:3000/emails/", {"email_address": self.email_address, "product_id": self.product_id, "user_id": user_id})
  end
end

app/models/login.rb
class Login < ApplicationRecord

end

app/models/product.rb
class Product
  attr_reader(:number, :name, :description, :image, :category, :product_items, :id, :related_products)

  def initialize(attributes)
    @number = attributes.fetch(:number)
    @name = attributes.fetch(:name)
    @description = attributes.fetch(:description)
    @image = attributes.fetch(:image)
    @category = attributes.fetch(:category)
    @product_items = attributes.fetch(:product_items)
    @id = attributes.fetch(:id)
    @related_products = attributes.fetch(:related_products)
  end

  def update_popularity
    RestClient.put("http://localhost:3000/products/#{self.id}", nil)
  end

  def self.get_products(category)
    if category == nil
      category = "products"
    end
    products = HTTParty.get("http://localhost:3000/#{category}").sort_by {|prod| prod["popularity"]}.reverse!
    returned_products = []
    products.each do |prod|
      if prod["image"] != "https://www.homelegance.com/wp-content/themes/h2/images/misc/shim.gif"
        returned_products.push(prod)
      end
    end
    return returned_products
  end

  def self.get_product(id)
    product = HTTParty.get("http://localhost:3000/products/#{id}")["product"]
    product_items = HTTParty.get("http://localhost:3000/products/#{id}")["product_items"]
    Product.new({id: product["id"], name: product["name"], number: product["number"], image: product["image"], description: product["description"], product_items: product_items, category: product["category"], related_products: product["related_products"]})
  end

end

app/models/product_item.rb
class ProductItem

  def self.get_product_items
    api = HTTParty.get("http://localhost:3000/product_items")
    api.each do |item|
      product = Product.where(number: item['product_number']).first
      product.product_items.create(description: item["description"], number: item["number"], price: item["price"].to_i, dimensions: item["dimensions"])
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.get_user(login, password)
    HTTParty.get("http://localhost:3000/users/#{login}/#{password}")
  end

  def update(user_params)
    RestClient.put("http://localhost:3000/users/#{user_params[:id]}", {"bedroom_mult": user_params[:bedroom_mult], "dining_mult": user_params[:dining_mult], "seating_mult": user_params[:seating_mult]})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_user
  def set_user
    if session[:user]
      @user = session[:user]
    else
      redirect_to '/login'
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index

  end

  def show
    @category = Category.find_by_name(params[:id])
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.all
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
  end

  # GET /emails/new
  def new
    @product_id = params[:product_id]
    @email = Email.new
  end

  # GET /emails/1/edit
  def edit
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(email_params)
    email = @email.send_email(session[:user]["user"]["id"])
    session[:user]["emails"].push(JSON.parse(email))
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /emails/1
  # PATCH/PUT /emails/1.json
  def update
    respond_to do |format|
      if @email.update(email_params)
        format.html { redirect_to @email, notice: 'Email was successfully updated.' }
        format.json { render :show, status: :ok, location: @email }
      else
        format.html { render :edit }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email.destroy
    respond_to do |format|
      format.html { redirect_to emails_url, notice: 'Email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_params
      params.require(:email).permit(:email_address, :product_id, :user_id)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :set_user
  def new
    @log = Login.new()
  end

  def create
    @user = User.get_user(params[:login][:login], params[:login][:password])
    session[:user] = @user
    redirect_to "/"
  end

private
  def login_params
    params.require(:login).permit(:login, :password)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.get_products(params[:category_id])
    @category = params[:category_id]
    if !params[:page]
      @page = 1
    else
      @page = params[:page]
    end
  end

  def show
    @product = Product.get_product(params[:id])
    @category = @product.category
    @page = params[:page]
    @sum = 0
    @multiplier = @user["user"][@category + "_mult"]
    if params[:sum]
      @product.product_items.each do |item|
        @sum = @sum + params[item['number']].to_i * item['price'].to_i * @multiplier
        params[:current_total] = @sum
      end
      respond_to do |format|
        format.html { redirect_to product_path(@product.number, category: @category) }
        format.js
      end
    end
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController

  def index

  end

  def show

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  skip_before_action :set_user, only: [:show]

  # GET /users/1
  # GET /users/1.json
  def show
    @user = session[:user]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      response = @user.update(user_params)
      if response
        session[:user] = JSON.parse(response)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    session[:user] = nil
    redirect_to '/'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.permit(:bedroom_mult, :dining_mult, :seating_mult, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgaFrontend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway" rel="stylesheet">
  </head>

  <body>
    <header>
      <%= yield(:back_location) %>
      <%= link_to '/' do %>
        <% if @category %>
          <h1 class="text-center">Browse <%= @category.capitalize %></h1>
        <% else %>
          <h1 class="text-center">Browse Furniture</h1>
        <% end %>
      <% end %>
      <ul style="list-style: none">
        <li style="display: inline-block; padding: 10px;">
          <%= link_to "/dining/1" do %>Dining<% end %>
        </li>
        <li style="display: inline-block; padding: 10px;">
          <%= link_to "/bedroom/1" do %>Bedroom<% end %>
        </li>
        <li style="display: inline-block; padding: 10px;">
          <%= link_to "/seating/1" do %>Seating<% end %>
        </li>
      </ul>
    </header>
    <div class="container">
      <%= yield %>
      <p style="position: absolute; z-index: 100;"><%= link_to "Logout", user_path(1), method: "delete" %></p>
    </div>
  </body>
</html>

app/views/logins/new.html.erb
<%= form_for(@log) do |f| %>
  <div class="form-group">
    <%= f.label :login%>
    <%= f.text_field :login, required: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label(:password )%>
    <%= f.password_field(:password, required: true, class: 'form-control' )%>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-default' %>
<% end %>

app/views/products/index.html.erb
  <% content_for(:back_location) do %>
    <%= link_to '/' do %>
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
    <% end %>
  <% end %>
  <div id="page-<%= @page %>" class="row product-row">
    <% @products.each_with_index do |product, index| %>
      <% if index < (6 * @page.to_i) && index >= (6 * (@page.to_i - 1)) %>
        <% if product["image"] != "https://www.homelegance.com/wp-content/themes/h2/images/misc/shim.gif" %>
          <%= link_to product_path(product["id"]) do%>
            <div class="col-lg-4 product">
              <div class="image" style="background: url(<%= product["image"] %>); background-size: cover; background-position: center center;"></div>
              <div class="info">
                <p><%= product["name"] %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>

<nav aria-label="Page navigation" class="text-center">
  <ul class="pagination">
    <li>
      <% if @page == '1' %>
        <%= link_to "/#{@category}/#{(@products.length/6).ceil}" do %>
          <span aria-hidden="true">&laquo;</span>
        <% end %>
      <% else %>
        <%= link_to "/#{@category}/#{(@page.to_i-1)}" do %>
          <span aria-hidden="true">&laquo;</span>
        <% end %>
      <% end %>
    </li>
    <% (@products.length/6).ceil.times do |time| %>
      <li <%if @page.to_i == time+1 %> class="active" <% end %>><%= link_to (time+1), "/#{@category}/#{(time+1)}" %></li>
    <% end %>
    <li>
      <% if @page.to_i == (@products.length/6).ceil %>
        <%= link_to "/#{@category}/1" do %>
          <span aria-hidden="true">&raquo;</span>
        <% end %>
      <% else %>
        <%= link_to "/#{@category}/#{(@page.to_i+1)}" do %>
          <span aria-hidden="true">&raquo;</span>
        <% end %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/products/show.html.erb
<% content_for(:back_location) do %>
  <%= link_to :back do %>
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
  <% end %>
<% end %>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-8">
    <img src="<%= @product.image%>" alt="Homelegance <%= @product.number %>" class="img-responsive" style="margin: 0 auto;">
  </div>
  <div class="col-lg-4">
    <h1><%= @product.name %></h1>
    <h3>Product Number: <%= @product.number %></h3>
    <p><%= @product.description %></p>
    <hr>
    <%= render "emails/form", email: Email.new() %>
  </div>
  <div class="clearfix"></div>
</div>
<div class="row">
  <div class="col-lg-8 item-pick">
    <h2 class="text-center">Pick Your Items</h2>
    <%= form_tag("/products/#{@product.id}", method: "get", remote: true) do |f| %>
    <table>
      <tr>
        <th>Item Description</th>
        <th>Dimensions</th>
        <th>Price</th>
        <th></th>
      </tr>
      <% @product.product_items.each do |item| %>
      <tr>
        <td><%= item["description"] %></td>
        <td><%= item["dimensions"] %></td>
        <td><%= number_to_currency(item["price"].to_i * @multiplier) %></td>
        <td>
          <div class="input-field col s12">
            <%= select_tag item["number"], options_for_select([[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8]]) %>
          </div>
          <%= hidden_field_tag :sum , true %>
          <%= hidden_field_tag :current_total , @sum %>
        </td>
      </tr>
      <% end %>
    </table>
    <%= submit_tag 'Get Price', class:'btn btn-default', style: 'float:right;' %>
    <% end %>
  </div>
  <div class="col-lg-4">
    <h2 id="total">Total: <%= number_to_currency(@sum) %></h2>
  </div>
</div>

<div class="related-products">
  <% @product.related_products.pop while @product.related_products.length > 4 %>
  <% @product.related_products.each do |id| %>
    <% product = Product.get_product(id) %>
    <%= link_to product_path(product.id) do%>
      <div class="col-md-3 product">
        <div class="image" style="background: url(<%= product.image %>); background-size: cover; background-position: center center;"></div>
        <div class="info">
          <p><%= product.name %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/show.js.erb
$(function(){
  $('#total').html('Total: <%= number_to_currency(params[:current_total]) %>')
})

app/views/splash/index.html.erb
<h1>Browse Categories</h1>
<div class="row">
  <%= link_to "/bedroom/1" do %>
    <div class="col-lg-4">
      <%= image_tag "https://www.homelegance.com/wp-content/uploads/2017/03/1968-1__1-750x500.jpg", class: "img-responsive" %>
      <h4 class="text-center">Bedroom Furniture</h4>
    </div>
  <% end %>
  <%= link_to "/dining/1" do %>
    <div class="col-lg-4">
      <%= image_tag "https://www.homelegance.com/wp-content/uploads/2016/02/586GY-82__11-750x500.jpg", class: "img-responsive" %>
      <h4 class="text-center">Dining Furniture</h4>
    </div>
  <% end %>
  <%= link_to "seating/1" do %>
    <div class="col-lg-4">
      <%= image_tag "https://www.homelegance.com/wp-content/uploads/2015/02/8427-3__1-750x500.jpg", class: "img-responsive" %>
      <h4 class="text-center">Seating</h4>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_tag "/users/#{@user["user"]["id"]}", method: :patch do  %>
  <table id="edit-table" class="table table-bordered" style="display: none;">
    <tr>
      <th>Category</th>
      <th>Multiplier</th>
    </tr>
    <tr>
      <td>Bedroom</td>
      <td><%= number_field_tag :bedroom_mult, @user["user"]["bedroom_mult"], class: "form-control", step: :any %></td>
    </tr>
    <tr>
      <td>Seating</td>
      <td><%= number_field_tag :seating_mult, @user["user"]["seating_mult"], class: "form-control", step: :any %></td>
    </tr>
    <tr>
      <td>Dining</td>
      <td><%= number_field_tag :dining_mult, @user["user"]["dining_mult"], class: "form-control", step: :any %></td>
    </tr>
  </table>
  <% hidden_field_tag :id, @user["user"]["id"] %>
  <%= submit_tag "Submit", class: "btn btn-default", id:"edit-submit" %>
<% end %>

app/views/users/edit.js.erb
$(function() {
  $("#mult-table").hide()
  $("#edit-table").show()
  $("#edit-submit").show()
})

app/views/users/index.html.erb
<h1>users</h1>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="text-center">User Settings</h1>
<h3>Customer Multipliers</h3>
<table id="mult-table" class="table table-bordered">
  <tr>
    <th>Category</th>
    <th>Multiplier</th>
  </tr>
  <tr>
    <td>Bedroom</td>
    <td id="bedroom"><%= @user["user"]["bedroom_mult"] %></td>
    <td><%= link_to("Edit", "/users/#{@user["user"]["id"]}/edit/bedroom", remote: true) %></td>
  </tr>
  <tr>
    <td>Seating</td>
    <td><%= @user["user"]["seating_mult"] %></td>
    <td><%= link_to("Edit", edit_user_path(@user["user"]["id"] ), remote: true) %></td>
  </tr>
  <tr>
    <td>Dining</td>
    <td><%= @user["user"]["dining_mult"] %></td>
    <td><%= link_to("Edit", edit_user_path(@user["user"]["id"]), remote: true) %></td>
  </tr>
</table>
<%= render "form" %>
<h3>Customer Product Emails:</h3>
<table class="table table-bordered">
  <tr>
    <th>Customer Email</th>
    <th>Product</th>
  </tr>
  <% @user["emails"].each do |email| %>
    <tr>
      <td><%= email["email_address"] %></td>
      <td><%= link_to("/products/#{email['product_id']}") do %><%= email["product_number"] %><% end %></td>
    </tr>
  <% end %>
</table>